services:
  galerna-build:
    image: galerna-stm32-build:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: bash
    tty: true
    stdin_open: true