name: Pull Request CI
on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker compose build galerna-build

      - name: Run test
        run: docker compose run --rm galerna-build cmake --workflow host-debug-build-and-test

      - name: Debug build
        run: docker compose run --rm galerna-build cmake --workflow stm32-debug-build

      - name: Release build
        run: docker compose run --rm galerna-build cmake --workflow stm32-debug-release